### ISSUE TITLE
Remove iAd static binding

### ISSUE THREAD

**Issue by mlynch** [driftyco/ionic-plugin-deeplinks#25]
iAd usage could result in rejected apps. Instead, infer at runtime if it's available.

**Comment by mlynch** [comment]
https://github.com/driftyco/ionic-plugin-deeplinks/tree/25-iad

**Comment by marcusforsberg** [comment]
I'm in the process of submitting an app to Apple for review, using the latest version of ionic-plugin-deeplinks. When asked about use of IDFA, I checked 'no' but when submitting I get this message: "Your app is using the Advertising Identifier (IDFA). You must either provide details about the IDFA usage or remove it from the app and submit your binary again.". Searching through my project, the line added in 394f3f4 is the only reference to `ASIdentifierManager` in my code, and I seem unable to submit the app because of this. Any ideas on how to get around this properly?
