### ISSUE TITLE
There is option to deep link with parent pages?

### ISSUE THREAD

**Issue by MatanYed** [driftyco/ionic-plugin-deeplinks#39]
There is a way, built-in in the plugin that can navigate to deep link with parent pages?

Let's say that is my deep link url: `example.com/product/cool-beans`

I want that to happened:

```
this.rootPage = HomePage;
this.navCtrl.push(ProductsPage);
this.navCtrl.push(ProductPage, { name: 'cool-beans' });
```

It means go to product page with 2 parent pages...

Sorry for bad english.

**Comment by mlynch** [comment]
Hey @MatanYed. Nothing built-in, but if you use the `route` function you should be able to do this easily. In fact, that was the intention of that feature so you can build any kind of history stack you want to display to the user.

Take a look at this demo: https://github.com/driftyco/ionic2-deeplinks-demo/blob/master/app/app.ts#L41

Instead of using `routeWithNavController`, just use `route` and then in the first callback do `this.navChild.push` twice with those pages.
