### ISSUE TITLE
My app never routes to the defined page

### ISSUE THREAD

**Issue by remithomas** [driftyco/ionic-plugin-deeplinks#4]
My app (Ionic2) and I tested the demo (ionic2-deeplinks-demo) don't route using **params**. 
example: 

> myapp://alert/42
> myapp://products/42 (for demo)

I got this error message
```
Unmatched Route
Object
$link: Object
host: "products"
path: "/1"
queryString: ""
scheme: "my app
url: "myapp://products/1"
```

They are working perfectly with a simple URL
example: 

> myapp://about-us

**Comment by remithomas** [comment]
Ok I found a way to soluce it: that should be with a prefix APP

> myapp://app/products/1instead of myapp://products/1i

Maybe without "app" it's better?!

**Comment by mlynch** [comment]
Hey @remithomas, you caught the gotcha. The issue I ran into is that, if you have more than one path item, the URL parser considers the first part the hostname. In this case, it thinks `products` is part of the host instead of the path.

To reduce any chance of odd behavior, I recommend using a filler host, like `app`. 

If that doesn't seem right let me know if you have thoughts and I can adjust.
