### ISSUE TITLE
problem route with Params

### ISSUE THREAD

**Issue by fx69005** [driftyco/ionic-plugin-deeplinks#63]
hi everyone, i use this plugin for my ionic1 project. the route of "myevents" works but when i used params into "detail" route, plugin say me "no-match" someone can explain me please ?
ps: my link for "detail" : myapp//detail/123456
```
$cordovaDeeplinks.route({
      '/detail/:id': {
        target: 'detail',
        parent: 'events'
      },
      '/myevents': {
        target: 'myevents',
        parent: 'events'
      }
    }).subscribe(function(match) {
      $timeout(function() {
        console.warn('match sucess', match);
        $state.go(match.$route.parent, match.$args);
        $timeout(function() {
          $state.go(match.$route.target, match.$args);
        }, 800);
      }, 100);
    }, function(nomatch) {
      console.warn('No match', nomatch);
    });
```

**Comment by FdezRomero** [comment]
You will need to add a host to your custom scheme URL, like `myapp://app/detail/123456` so the plugin takes `app` as the host and the path `/detail/123456` matches yours. You can replace `app` with whatever you want.

**Comment by fx69005** [comment]
works great now !  really thanks for your contribution !

**Comment by ratchakrit** [comment]
Can I ask you what "app" should be because I try to change in many way but still not working.

Here is my code:

'/myEvents': {
        target: 'myEvents',
        parent: 'menu'
}
'/app/eventDetail/{id}': {
        target: 'eventDetail',
        parent: 'menu'
}

I try to access to this schema:
myappname://app/eventDetail/35 this return "no match"
myappname://myEvents "This return expected result"


But It still no match. Please guide me.
My deep Host is "api.mywebsite.com" but there is nothing on api.mywebsite.com Do I need to do something on that host?
